apiVersion: v1
kind: Service
metadata:
  name: lca-api-service
  namespace: legacy-code-archaeology-dev
  labels:
    app: lca-api
spec:
  selector:
    app: lca-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
