apiVersion: v1
kind: ConfigMap
metadata:
  name: lca-config
  namespace: legacy-code-archaeology-dev
data:
  SPRING_PROFILES_ACTIVE: "openshift"
  SERVER_PORT: "8080"
  LCA_LLM_EXTERNAL_SEND: "false"
