apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: legacy-code-archaeology-dev
resources:
  - namespace.yaml
  - configmap.yaml
  - postgresql-pvc.yaml
  - postgresql.yaml
  - neo4j-pvc.yaml
  - neo4j.yaml
  - api-deployment.yaml
  - api-service.yaml
  - api-route.yaml
