apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lca-neo4j-pvc
  namespace: legacy-code-archaeology-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd-immediate
