apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lca-postgresql-pvc
  namespace: legacy-code-archaeology-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
